version: "3.6"
services:
  mongo:
    image: mongo
    container_name: nextjs-authentication-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - next-authentication:/data/db
volumes:
  next-authentication:
